### ISSUE TITLE
Error this.getDirectoryCTime undefined when run on macOS

### ISSUE THREAD

**Issue by codingwatching** [sciner/webcraft#12]
Hi @sciner 
I checkout the latest commit and run but i got this error on macOS:
```
Last login: Fri Sep  3 23:38:13 on ttys000
apple@Apples-iMac webcraft % go run ./main.go 
# whiteframe.ru/webcraft/Type
Type/World.go:37:24: this.getDirectoryCTime undefined (type *World has no field or method getDirectoryCTime)
apple@Apples-iMac webcraft % 
```

**Comment by ivanpopelyshev** [comment]
Yo, @codingwatching ! Just a comment, this repo is in active development :) We didnt test it on macOS so your input is very appreciated

**Comment by sciner** [comment]
Thanks for your help.
Issue fixed in commit:
https://github.com/sciner/webcraft/commit/6fd209cd0f75fc401e04f65396f883e95d65a864

**Comment by codingwatching** [comment]
@sciner It works like a charm! Thank you!
