### ISSUE TITLE
World not build when create new game

### ISSUE THREAD

**Issue by codingwatching** [sciner/webcraft#2]
Hi @sciner 
I just start the server and run http://localhost:5700
I can see the world in Demo Server mode
But when creating a new game, I only see the sky, no blocks

![image](https://user-images.githubusercontent.com/85933804/125984435-f1a8e23c-fe29-4fd9-8ae7-8ae578e684a1.png)

![image](https://user-images.githubusercontent.com/85933804/125984700-82338f2d-8e65-4f65-8662-a7df4a4b0b58.png)

**Comment by sciner** [comment]
Because in your session saved old format coordinates (xyz not xzy).
Clear browser cache and local storage then run again.

**Comment by codingwatching** [comment]
@sciner Thank you so much!
