### ISSUE TITLE
Can we build and run client on android device

### ISSUE THREAD

**Issue by codingwatching** [sciner/webcraft#32]
Hi there!
Can we wrap around the client with some game engine to build a "native feeling like" android client?
So we can reach more users and have the mobility of playing this game (like https://www.classicube.net/)
Thank you so much! 
WebCraft is really an awesome project!

**Comment by ivanpopelyshev** [comment]
Hello! There are multiple technical problems with this

Controls. we need mobile controls on this thing first.

Its not possible to put this in real game engines, you have to do a HUGE refactoring for this, and you'll make code much more difficult. Current renderer is suited for minecraft-like game, i dont know if you find same abstractions in other renderers.
Even game logic - its developing very fast, and i dont know how will you be able to merge it in version that does use game engines.

I dont know about electron and stuff  - if you have experience with it - please try make PR with proper configs and we'll look at it :)

**Comment by codingwatching** [comment]
Hi @ivanpopelyshev Thank you for the detailed explanation. 
I am happy to play it in the browser for now
